<a href="https://colab.research.google.com/github/erhansozen/Assignments-LearningPortfolio/blob/main/Assignment_3_%7C_hommework_3_student_ipynb_adl%C4%B1_not_defterinin_kopyas%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
from fastai.vision.all import *
from fastbook import *
fastbook.setup_book()

# Introduction to Artificial Neural Networks

Please read the introdcution of neuronal networks of the book *Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow*, p. 299-316.

❓ Why have neural networks, even though they were invented early on, only now caught on?

✈


❓ What is a percepton and a threshold logic unit (TLU)? Try to define a linear function and a step function of your choice, use some values of your choice and explain what might be the result of the percepton. (maybe using max. two TLU's)

✈ Perception is one of the simplest Artificial Neural Network architectures. It is based on a slightly different artificial neuron called Threshold Logic Unit (TLU).

❓ What is a fully connected layer and a output layer? Why can we easily combine the equations of multiple instances into a fully connected layer?

✈ A perceptron is composed of one or more TLUs organized in a single layer, where every TLU is connected to every input. This layer is called a FULLY CONNECTED LAYER. TLUs layer that gives the outputs is called output layer. SYF 333'de sayfanın alt kısmında cevap

❓ What problem did Marvin Minsky and Seymour Paper highlight that perceptrons could not solve? What is a possible solution?

✈ They figured out the incapable of solving some trivial problems classification problem of perfecptrons. Then they find out perceptrons turn out that some of the limitations of perceptrons can be eliminated by stacking multiple perceptrons. This ANN architecture is called a MULTILAYER PERCEPTRONS (MLP)

❓ What is a deep neuronal network? What are hidden layers? What means feedforward neural network (FNN).

✈This multilayer perceptrons (MLP) are consist of one input layer and one or more layers of TLUs, and they are called HIDDEN LAYERS. When an ANN contains a deep stack of hidden layers, it is called a DEEP NEURAL NETWORK (DNN)


❓ Try to explain how backpropagation works! (In Addition, you can have a look to the following example, which tries manually to compute the backprogation of a simple linear network. https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/ OR you can also read through the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy))

✈ Backpropagation is combined with reverse-mode autodifferentiation and gradient descent. Reverse-mode autodiff is a technique that compute all the gradients automatically and efficently. Two passes through the neural network is able to compute the gradients of the neural network's error with regard to every single model parameter. These gradients can be used to perform a gradients descent step. Then you repeat this process of computing the gradients automatically and taking a gradient descent step, the neural network's error will gradually drop until it eventually reaches a minimum. This combination of reverse-mode auto diff and gradient descent is called BACKPROPAGATION.


❓ Why do we need activation functions, wouldn't it be easier just using linear functions?

✈ Backpropagation algorithm works well with activation functions. If you have some nonlinearity between layers, then even a deep stack of layers is equivalent to a single layer and you can't solve very complex problems with that.


## Ideas for the learning portfolio: 

1) For example, you could train a single TLU to classify iris flowers based on petal length and width in the !!!pyTorch!! environment.

2) You could add to our king county housepricing ML project a neuronal network and compare it to the other models. 

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

# A traditional approach: training a digit classifier and learning pyTorch tensors.

For this assignment, I ask you to read the Google Colab [04_mnist_basics.ipynb](https://colab.research.google.com/github/fastai/fastbook/blob/master/04_mnist_basics.ipynb#scrollTo=t1DK6o-gckCy) to the beginning of the chapter *Stochastic Gradient Descent (SGD)*. 

First, try to summarize what we know about pyTorch tensors by trying to predict whether we have a 1 or a 7 in the MNIST dataset using a traditional rule-based programming approach. Therefore use pyTorch tensors for the entire tasks and fulfill the following steps:

1) Randomly split the MNIST dataset (1 and 7) into a training dataset and a test dataset in a ratio of 80:20.

2) Instead of using an optimal 1 or 7 with the mean over the training dataset, try to calculate the sum of the distances to all instances in the training set for each instance in the test dataset. You can use the L2 norm. 

3) For each instance in the test set, decide if it is a 1 or 7 and calculate the precision.

Do we get a similar good result?


In [1]:
# YOUR TASK
#hide
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
fastbook.setup_book()
#hide
from fastai.vision.all import *
from fastbook import *

matplotlib.rc('image', cmap='Greys')
path = untar_data(URLs.MNIST_SAMPLE)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 kB 9.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 45.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 kB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 5.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 16.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 kB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [2]:
Path.BASE_PATH = path
path.ls()
(path/'train').ls()

(#2) [Path('train/7'),Path('train/3')]

In [3]:
threes = (path/'train'/'3').ls().sorted()
sevens = (path/'train'/'7').ls().sorted()
threes

(#6131) [Path('train/3/10.png'),Path('train/3/10000.png'),Path('train/3/10011.png'),Path('train/3/10031.png'),Path('train/3/10034.png'),Path('train/3/10042.png'),Path('train/3/10052.png'),Path('train/3/1007.png'),Path('train/3/10074.png'),Path('train/3/10091.png')...]

In [4]:
im3_path = threes[1]
im3 = Image.open(im3_path)
im3

# Stochastic Gradient Descent (SGD)

For this exercise I ask you to read the chapter Stochastic Gradient Descent (SGD) from the Google Colab 04_mnist_basics.ipynb in paralell. The chapter starts with a single TLU, compare p. 304 in "Hands on Machine Learning". Go through all 7 steps which are an easy example of how Stochastic Gradient Descent works.

Our goal is to train a single TLU, which can decide if one number is larger then the other one. Therefore we create 100 random pairs with pyTorch and create a target vector which is eather 1 or 0.


In [5]:
x = torch.randn((100, 2))
y = torch.where(x[:,0] > x[:,1], 1.0, 0.0)
print(x)
print(y)

tensor([[ 1.9269e+00,  1.4873e+00],
        [ 9.0072e-01, -2.1055e+00],
        [ 6.7842e-01, -1.2345e+00],
        [-4.3067e-02, -1.6047e+00],
        [-7.5214e-01,  1.6487e+00],
        [-3.9248e-01, -1.4036e+00],
        [-7.2788e-01, -5.5943e-01],
        [-7.6884e-01,  7.6245e-01],
        [ 1.6423e+00, -1.5960e-01],
        [-4.9740e-01,  4.3959e-01],
        [-7.5813e-01,  1.0783e+00],
        [ 8.0080e-01,  1.6806e+00],
        [ 1.2791e+00,  1.2964e+00],
        [ 6.1047e-01,  1.3347e+00],
        [-2.3162e-01,  4.1759e-02],
        [-2.5158e-01,  8.5986e-01],
        [-1.3847e+00, -8.7124e-01],
        [-2.2337e-01,  1.7174e+00],
        [ 3.1888e-01, -4.2452e-01],
        [ 3.0572e-01, -7.7459e-01],
        [-1.5576e+00,  9.9564e-01],
        [-8.7979e-01, -6.0114e-01],
        [-1.2742e+00,  2.1228e+00],
        [-1.2347e+00, -4.8791e-01],
        [-9.1382e-01, -6.5814e-01],
        [ 7.8024e-02,  5.2581e-01],
        [-4.8799e-01,  1.1914e+00],
        [-8.1401e-01, -7.359

Your task is to create a function f that is a single TLU, meaning that it summarizes x with weights a, b, c:

$ax_0+bx_1+c$

In Addition we are using a *sigmoid()* function as step function.

$f = \text{sigmoid}(ax_0+bx_1+c)$

✈ We want to distinguish clearly between the function's input (the time when we are measuring the coaster's speed) and its parameters (the values that define which quadratic we're trying). So, let's collect the parameters in one argument and thus separate the input, t, and the parameters, params, in the function's signature

✈ In other words, we've restricted the problem of finding the best imaginable function that fits the data, to finding the best quadratic function. This greatly simplifies the problem, since every quadratic function is fully defined by the three parameters a, b, and c. Thus, to find the best quadratic function, we only need to find the best values for a, b, and c.

In [9]:
def f(x, params):
    a,b,c = params
    return a*(x**2) + (b*x) + c

print(f(x, [3,-2,1]))

tensor([[ 8.2852,  4.6615],
        [ 1.6324, 18.5107],
        [ 1.0239,  8.0414],
        [ 1.0917, 11.9342],
        [ 4.2014,  5.8574],
        [ 2.2471,  9.7176],
        [ 4.0452,  3.0577],
        [ 4.3110,  1.2191],
        [ 5.8070,  1.3956],
        [ 2.7370,  0.7005],
        [ 4.2406,  2.3317],
        [ 1.3222,  6.1122],
        [ 3.3502,  3.4493],
        [ 0.8971,  3.6751],
        [ 1.6242,  0.9217],
        [ 1.6930,  1.4984],
        [ 9.5213,  5.0196],
        [ 1.5964,  6.4133],
        [ 0.6673,  2.3897],
        [ 0.6690,  4.3492],
        [11.3932,  1.9826],
        [ 5.0816,  3.2864],
        [ 8.4187, 10.2731],
        [ 8.0424,  2.6900],
        [ 5.3329,  3.6157],
        [ 0.8622,  0.7778],
        [ 2.6904,  2.8753],
        [ 4.6158,  4.0970],
        [ 9.7138,  0.9319],
        [ 1.1390,  1.0181],
        [ 1.2243,  7.5184],
        [ 7.5785,  3.9755],
        [ 4.3750,  1.4875],
        [11.3234,  0.7748],
        [ 0.6672,  1.5115],
        [ 6.4457,  3

In addition to our TLU function, we need a loss function. Your task is to implement a absolute difference loss function, $∑|x_i-y_i|$, which counts the number of wrong guesses.

In [10]:
def mae(preds, targets): return ((preds-targets)**2).mean()

Try to train your single TLU with the absolute difference loss function, use the following code. Choose an appropriate step weight `lr` and try to explain what is happing in each line.

In [17]:
lr = 1
params = torch.randn(3).requires_grad_()

def apply_step(params, prn=True):
    preds = f(x, params)
    loss = mae(preds, y)
    loss.backward()
    params.data -= lr * params.grad.data
    params.grad = None
    if prn: print(params);print(loss.item())
    return preds


for i in range(50): apply_step(params)

RuntimeError: ignored

Write a line of code that counts the number of wrong predictions, rounding your predictions with *round()*.

In [19]:
preds = f(x, params)
preds.round()

tensor([[ 1.,  1.],
        [ 1., -6.],
        [ 1., -3.],
        [-0., -4.],
        [-2.,  1.],
        [-1., -3.],
        [-1., -1.],
        [-2.,  1.],
        [ 1., -0.],
        [-1.,  1.],
        [-2.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [-0.,  0.],
        [-0.,  1.],
        [-3., -2.],
        [-0.,  1.],
        [ 0., -1.],
        [ 0., -2.],
        [-4.,  1.],
        [-2., -1.],
        [-3.,  1.],
        [-3., -1.],
        [-2., -1.],
        [ 0.,  1.],
        [-1.,  1.],
        [-2., -1.],
        [-3.,  0.],
        [-0.,  1.],
        [-0.,  1.],
        [-3.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1., -0.],
        [-2.,  1.],
        [-0.,  1.],
        [ 0.,  1.],
        [ 1., -1.],
        [-6., -2.],
        [ 0., -1.],
        [-3., -1.],
        [ 1.,  1.],
        [ 1.,  0.],
        [ 1., -1.],
        [-2.,  1.],
        [-4., -2.],
        [ 1.,  1.],
        [-7.,  1.],
        [ 1.,  0.],
